### PR TITLE
Added logging of the event if feature extractor failed

### PR DESCRIPTION
**Pull request by BloodAxe**

### CODE REVIEW

**Review by Louis-Dupont — COMMENTED** [review]
LGTM, but do you have a screenshot of how it looks ? 
I am just afraid that it would show the full traceback over multiple lines, and this may look messy.

**Comment by BloodAxe** [comment]
It currently looks like this:
Messy, but you def. not will miss it. 
image

**Review by Louis-Dupont — COMMENTED** [review]
LGTM

**Review by ofrimasad — APPROVED** [review]
LGTM

**Pull request merged**
